version: '2'
volumes:
    sense-data:
services:
  InfluxDB:
    restart: always
    build: ./influxdb
    volumes:
      - 'sense-data:/data'
  Grafana:
    restart: always
    build: ./grafana
    ports:
      - "80"
    volumes:
      - 'sense-data:/data'
    environment:
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_PATHS_PROVISIONING=/usr/src/app/provisioning'
        - 'GF_SESSION_PROVIDER=memory'
    depends_on:
      - InfluxDB
  GeigerCounter:
    build: ./pijuice
    privileged: true
    labels:
      io.balena.features.dbus: '1' 
  wifi-connect:
      build: ./wifi-connect
      network_mode: "host"
      labels:
          io.balena.features.dbus: '1'
      cap_add:
          - NET_ADMIN
      environment:
          DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
